title: CAyman theme
#logo: /assets/img/headshot_circle.png
description: I am a final-year B.Tech CSE - Data Science student with an interest in Data Science and am passionate about using advanced analytics to drive innovation and solve complex challenges.
show_downloads: false
link: https://www.linkedin.com/in/g-s-chaitanya
link: https://github.com/chaitanya2173
#theme: jekyll-theme-hacker
#theme: jekyll-theme-minimal
theme: jekyll-theme-cayman
#theme: jekyll-theme-time-machine
